project_id = "envjjulupltdixvericz"

[functions.run-qos-test]
verify_jwt = true

[functions.seed-services]
verify_jwt = false

[functions.get-recommendations]
verify_jwt = true

[functions.compare-services]
verify_jwt = true

[functions.test-service]
verify_jwt = true

[functions.predict-qos]
verify_jwt = true

[functions.sync-publicapis]
verify_jwt = false

[functions.create-web-service]
verify_jwt = true

[functions.token-check-demo]
verify_jwt = true

[functions.payments-create-order]
verify_jwt = true

[functions.payments-verify]
verify_jwt = true

[functions.payments-webhook]
verify_jwt = false
